# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0002_dj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='info',
            field=models.CharField(max_length=8192),
        ),
    ]
