# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-21 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0003_auto_20190420_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='price',
            field=models.IntegerField(),
        ),
    ]
