# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0004_auto_20190421_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='price',
            field=models.FloatField(),
        ),
    ]
